# Generated by Django 4.1.7 on 2023-03-03 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='name',
            new_name='country',
        ),
    ]
