# Generated by Django 4.1.7 on 2023-03-06 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_rename_name_country_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
